x = int(input('enter the value of x = '))
y = int(input('enter the value of t = '))
add = (x + y)
sub = (x - y)
mul = (x * y)
div = (x / y)
div1 = (x // y)
mod = (x % y)
exp = (x ** y)
print(add)
print(sub)
print(mul)
print(div)
print(div1)
print(mod)
print(exp)
